### ISSUE TITLE
Document g:asyncrun_timer or default to -1

### ISSUE THREAD

**Issue by RedBeard0531** [skywind3000/asyncrun.vim#5] opened 2016-10-10 18:58 UTC
I found the delay in updating the quickfix list annoying so in my .vimrc I do 

```VimL
" Update :AsyncRun output as it is ready rather than waiting on timer.
let g:asyncrun_timer = -1
```

The code makes it look like this is supposed to work, so I'm wondering why it isn't the default or at least documented. It seems to work for me... (famous last words, I know)

**Comment by skywind3000** [comment] 2016-10-10 19:35
Yes, you are right, asyncrun has two mode: buffer mode (by default) and immediate mode.

#### immediate mode: `g:asyncrun_timer` <= 0 (not default)
every thing child process output are immediately redirect to quickfix windows.
this is fast, I know.

but if some job continue output information (eg. gcc STL error), flooding the 
quickfix window will cause vim unresponsed (ui freeze), vim has no time to process other events or update ui.

Just like doing some long-time-job in windows application's ui thread will get it's window freeze.

#### buffer mode: `g:asyncrun_timer` > 0 (by default)
read stdout/stderr from child process and get them buffered, until each interval, 
fetch some lines from buffer and append them to quickfix.

So, there is an interval, populating quickfix window slowly each time will give vim enough time to do 
other stuff (updating ui, eg).

It is a little complicate, so I haven't documented them.

------
The problem is the default period was a bit long (about 1 second), so I have update a new version with a smaller period (100 millisec). hope it will work for you without modifying `g:asyncrun_timer`.

**Comment by skywind3000** [comment] 2016-10-10 19:39
could you please remove modifying `g:asyncrun_timer` and update asyncrun to the latest version,
and leave some feed back here ?

**Comment by RedBeard0531** [comment] 2016-10-10 19:49
So far, I've been happy with vim's responsiveness even when there are crazy STL errors (I'm using this on a c++ project).

Using the lower timer is faster but is still noticeably "chunky" relative to unbuffered mode. However there is a different and more concerning problem I've found. With "fast buffered" mode it is basically impossible to scroll up even if the output is silent because it constantly moves the cursor to the last line. With unbuffered mode, it only moves the cursor on new output. Ideally, it would only scroll to the new end if the cursor is currently on the (former) last line. Is that possible?

The programmer in me always prefers triggered events to polling, but I can get over that if there are usability issues with continuous updating. :)

**Comment by skywind3000** [comment] 2016-10-10 20:06
Thanks very much.

updated another new version:
1. fixed constantly auto scrolling in "fast buffered" mode.
2. change default mode to unbuffered mode.

----------
>  Ideally, it would only scroll to the new end if the cursor is currently on the (former) last line. Is that possible?

I have discussed it a lot at https://groups.google.com/forum/#!forum/vim_dev 
and Bram created a new `:cbottom` for me to get quickfix window scrolled to bottom.

Somebody proposed the same solution just like yours.

Unfortunately, Bram thought it is impossible, because, at first with an empty quickfix window,
cursor is on line 1, after adding one line to quickfix, cursor will move to line 2, and in that mode, cursor will continue moving to the last line and get window scrolled.

So without the help of Bram, this feature is impossible now.

**Comment by RedBeard0531** [comment] 2016-10-10 21:59
Thanks. I futzed around with it a bit and I think I found a solution to both the possible responsiveness issues (read up to 10 lines at a time) and scrolling only if at the last line. Should I open a pull request? My vimscript skills are pretty rough so feel free to just take the idea and implement it correctly.

```diff
diff --git a/plugin/asyncrun.vim b/plugin/asyncrun.vim
index 2826513..99c84f2 100644
--- a/plugin/asyncrun.vim
+++ b/plugin/asyncrun.vim
@@ -209,6 +209,7 @@ endfunc
 
 " invoked on timer or finished
 function! s:AsyncRun_Job_Update(count)
+        let l:scolled_in_qf = &ft=='qf' && line('.') != line('$')
        let l:count = 0
        let l:total = 0
        while s:async_tail < s:async_head
@@ -224,7 +225,7 @@ function! s:AsyncRun_Job_Update(count)
                        break
                endif
        endwhile
-       if s:async_scroll != 0 && l:total > 0
+       if s:async_scroll != 0 && l:total > 0 && !l:scolled_in_qf
                call s:AsyncRun_Job_AutoScroll()
        endif
        return l:count
@@ -249,8 +250,18 @@ function! g:AsyncRun_Job_OnCallback(channel, text)
        if a:text == ''
                return
        endif
-       let s:async_output[s:async_head] = a:text
-       let s:async_head += 1
+
+        " Read up to 10 lines at a time if they are ready before redrawing
+        let l:line = a:text
+        for l:ignored in range(10)
+            let s:async_output[s:async_head] = l:line
+            let s:async_head += 1
+
+            let l:line = ch_read(a:channel, {'timeout': 0})
+            if type(l:line) != 1 || l:line == ''
+                break
+            endif
+        endfor
        if g:asyncrun_timer <= 0
                call s:AsyncRun_Job_Update(-1)
        endif
@@ -259,6 +270,7 @@ endfunc
 " because exit_cb and close_cb are disorder, we need OnFinish to guarantee
 " both of then have already invoked
 function! s:AsyncRun_Job_OnFinish(what)
+        let l:scolled_in_qf = &ft=='qf' && line('.') != line('$')
        " caddexpr '(OnFinish): '.a:what.' '.s:async_state
        if s:async_state == 0
                return -1
@@ -290,7 +302,7 @@ function! s:AsyncRun_Job_OnFinish(what)
                let g:asyncrun_status = "failure"
        endif
        let s:async_state = 0
-       if s:async_scroll != 0
+       if s:async_scroll != 0 && !l:scolled_in_qf
                call s:AsyncRun_Job_AutoScroll()
        endif
        let g:asyncrun_code = s:async_code

```

On a related note, I use an autocmd to open the QuickFix window whenever it is written to: https://github.com/RedBeard0531/dot_files/blob/master/vimrc#L223. The QuickFixCmdPost event didn't fire on cexpr and friends, but that was fixed in one of the last patches to go in before 8.0.

**Comment by skywind3000** [comment] 2016-10-11 03:45
that's a good idea, and I have some comments here:
1. If quickfix window is not the current window, this code will get quickfix window always scrolled, right ? it will not check the cursor line number unless I jump to the quickfix window ? should it always detect the lineno no matter what current window I am in ?
2. `s:AsyncRun_Job_AutoScroll` is also invoked after "[Finished in xxx seconds]" when job stop, which has no check on current cursor line number. miss ?

**Comment by skywind3000** [comment] 2016-10-11 14:30
I have updated a new version to enable this feature, if you set `g:asyncrun_last` to non-zero, quickfix window will scroll only if the cursor is on the last line.
consider to performance problem, `g:asyncrun_last` is set to zero by default, you can turn it on manually.

**Comment by RedBeard0531** [comment] 2016-10-11 16:08
1. I initially tried using windo to scan all windows to find the quickfix win, but I didn't like how it moved my cursor. I thought about it for a bit and realized that I probably want it to scroll when I'm not in the qf window anyway. My thinking is that I'm either actively looking through the qf list and I want to stay where I am, or I'm doing something else and I just want to see the latest output so I know when it is done. The fact that it performs better is an added bonus.

2. I thought I got all of them. As I said, it was kinda a quick hack job.

I just tried your updated version with g:asyncrun_last=1 and it made vim unusably unresponsive. I was unable to leave scroll up or leave the qf window. I'm not sure what the cause of the problem was, but even killing my compile job lift vim seemingly hung using >100% cpu. I've gone back to my patched version for now.

Also I've found that always calling `cbottom` causes the completion popup to flicker in an annoying way (I use YCM so it is often visible). I've worked around this by making `s:AsyncRun_Job_AutoScroll` return immediately if `pumvisible()`. Maybe it would be better to just never call cbottom when in insert mode. I do force it to always scroll from the finished callback by passing a `force` argument, so that I don't miss completion.

If you think this is too special-case or my usage doesn't match yours, I'm fine maintaining a forked version that matches my (possibly weird) needs. This is a nice plugin and it will be easy to make it bend to my will. ;)

**Comment by skywind3000** [comment] 2016-10-11 17:20
Your idea maybe a good choice for someone too, so I have updated another version again:
1. due to performance issue, make buffered mode default again.
2. add some modes to `g:asyncrun_last`, which can be [FOUND HERE ...](https://github.com/skywind3000/asyncrun.vim/wiki/Scroll-the-quickfix-window-only-if-cursor-is-on-the-last-line)

If it still can not fit your need, feel free to fork a new version and make your own one.

**Comment by skywind3000** [comment] 2016-10-12 03:55
update again, 
by default, quickfix window will always scroll, unless current window is a quickfix window and the cursor isn't on the last line.

it is unnecessary to config g:asyncrun_last for most users.  but you still can config it when needed.

[THIS PAGE](https://github.com/skywind3000/asyncrun.vim/wiki/Scroll-the-quickfix-window-only-if-cursor-is-on-the-last-line) has been updated too.

**Comment by skywind3000** [comment] 2016-10-26 07:02
closing if there is not further question.

**Closed by skywind3000** 2016-10-26 07:02 UTC
