### ISSUE TITLE
Incorrect background job status

### ISSUE THREAD

**Issue by junkblocker** [skywind3000/asyncrun.vim#25] opened 2016-12-19 00:05 UTC
Sometimes ``AsyncRun`` gets stuck thinking the background job is still running and won't allow further runs of the job. 

```
ERROR: background job is still running
```

Verified that the process ran isn't running. ``AsyncStop`` doesn't seem to help.

MacVim 8.0.134

**Comment by skywind3000** [comment] 2016-12-19 12:07
I will inspect it. Do you have any clue to reproduce it ?

**Comment by skywind3000** [comment] 2016-12-19 12:18
Does ":AsyncStop!" help (AsyncStop with a "!" ) ?

**Comment by skywind3000** [comment] 2016-12-19 12:37
The latest [MacVim](https://github.com/macvim-dev/macvim/releases) includes only 8.0.124.
How can you use 8.0.134 ??

**Comment by junkblocker** [comment] 2016-12-19 15:28
I am not doing anything special. I have a command run on every document save. After a while the problem appears. It is possible that at some point MacVim stopped responding to input and I had to Ctrl+C a few times it which got it unstuck but that maybe prevents some state cleanup. No I don't see the message in quickfix window.

I built MacVim myself applying patches from upstream also (all scripted away). So usually have newer versions that officially available MacVim build.

I'll try `AsyncStop!` next time the problem appears.

**Comment by sir-pinecone** [comment] 2017-10-16 15:32
I have this same problem and it's starting to make me a little crazy. I use this plugin to run a build script so that I can quickly compile the code I'm editing. I just updated the plugin today and the frequency of the jobs getting stuck has gone up.

I tried `AsyncStop!` and it doesn't help, nor does `AsyncStop`. 

My build command is: `nnoremap <leader>b :AsyncRun! -save=2 ./build*<cr>` with `build*` being some shell script that kicks off a MSVC process. I see the [Finished in X seconds] message and a success status. I don't know how to consistently recreate the bug though. It just seems to randomly happen and I have to close vim to get it working again.

I'm using vim 8.0 with patches 1-606 on Windows 7. I built it myself.

**Comment by sir-pinecone** [comment] 2017-10-16 15:35
I also have another command that sometimes triggers this bug:

```
function! HideAsyncResults()
  call asyncrun#quickfix_toggle(g:build_window_size, 0)
endfunction

function! SilentBuild()
  AsyncStop
  exec "AsyncRun! -save=2 -post=call\\ HideAsyncResults() ./build*"
endfunction

nnoremap <F8> :call SilentBuild()<cr>
```

I wonder if the -save=2 flag is the culprit. I'm going to remove it for a bit and see if that helps.

**Comment by sir-pinecone** [comment] 2017-10-16 15:47
I noticed that if I get into the stuck state and then try to reload my vimrc using `so $MYVIMRC` I get this error: `Error detected while processing function AsyncRun_Job_OnTimer[11]..<SNR>51_AsyncRun_Job_Update:`

Followed by these two errors repeatedly until I close vim
```
E716: Key not present in Dictionary: raw == 1
E15: Invalid expression: s:async_info.raw == 1
```

**Comment by skywind3000** [comment] 2017-10-17 06:32
don't press ctrl-c

**Comment by sir-pinecone** [comment] 2017-10-17 12:22
> don't press ctrl-c

Can you please be more specific? I don't recall pressing ctrl-c at any point when experiencing the stuck job state I described above.

**Comment by antoinemadec** [comment] 2017-12-21 01:15
I have the same issue on Ubuntu16.04, vim 8.0.14.18 (complied today).
The issue happens only if the command is executed super fast.

For instance, **the following command works fine** and can be repeated as many time as I want:
`  :AsyncRun sleep 1; echo foo`

However, **the second execution of the follwing command will trigger the error** "ERROR: background job is still running":
`  :AsyncRun echo foo`
**The first execution does not print [Finished in ? seconds].**
Also, `AsyncStop!` does not help.

Do you know what that could be ?
Thanks for the excellent plugin anyway :)

Antoine

**Comment by skywind3000** [comment] 2017-12-21 03:51
sorry, it can't be reproduced on my debian / cygwin and mac os x.
Could you try to disable other plugins temporarily before invoking AsyncRun ?

**Comment by antoinemadec** [comment] 2017-12-21 17:58
Thanks for the quick response.
I did some investigation, here is the minimal vimrc to reproduce the bug:
```
call plug#begin('~/.vim/plugins_by_vimplug')
Plug 'skywind3000/asyncrun.vim'
call plug#end()
set nocompatible

autocmd BufWinEnter * call system("sleep 1")
```

Also, you have to add copen | to trigger the issue:
`:copen | AsyncRun echo foo`

Running that command will trigger **autocmd system("sleep 1")**, **echo foo** finishes first, hence the bug.

I hope this help,
Antoine

**Comment by antoinemadec** [comment] 2017-12-22 00:38
`:help job` says:
Note that if the job exits before you read the output, the output may be lost.
This depends on the system (on Unix this happens because closing the write end
of a pipe causes the read end to get EOF).  To avoid this make the job sleep
for a short while before it exits.

**Comment by antoinemadec** [comment] 2018-01-17 19:42
@skywind3000 , do you have any news about this bug ?
Were you able to reproduce it ?

**Closed** 2018-02-08 04:49 UTC

**Comment by skywind3000** [comment] 2018-02-08 07:42
I have changed the order of some variable assigment for better state handling.

**Comment by antoinemadec** [comment] 2018-02-08 18:11
Your latest commit has been tested and works as well.
Thanks a lot !

**Comment by sir-pinecone** [comment] 2018-02-08 23:56
Thanks so much @antoinemadec, you rock! And thanks @skywind3000 for the awesome plugin.

**Comment by woshichuanqilz** [comment] 2020-10-27 13:42
I still have this issue, just install the Asyncrun today.
It happens when I edit the vimrc(init.vim) file then I run command 
AsyncRun alacritty, alacritty started, then come back to the previous nvim window, then press `:w` to save the file.
Error shows:
Error detected while processing function AsyncRun_Job_OnTimer[11].<SNR>57_AsyncRun_Job_Update:
line 12:
E716 Key not prsent in Dictionary: errorformat

how to solve this?

nvim v0.4.4
Manjaro 20.1.2 Mikah

**Comment by stewartimel** [comment] 2021-07-19 22:03
Same here. My issue happens if I reload my init.vim file while in vim:
:source init.vim
When I run a :w, it shows the "Error: background job is still running".

This is my AsyncRun command in my init.vim:
au BufWritePost * :AsyncRun sh generate_tags.sh

Thanks for the help!
